pipeline {
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Ovejazo/Tingeso.2.git']])
                dir("payroll-frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }

        stage('Build and Push Docker Image'){
            steps{
                dir("payroll-frontend"){
                    script{
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t ovejazo/payroll-frontend:latest ."
                            bat "docker push ovejazo/payroll-frontend:latest"
                        }
                    }
                }
            }
        }
    }
}   
